### ISSUE TITLE
Handle single Lancelot selection

### ISSUE THREAD

**Issue by Quenty** [DylanDmitri/spamalot#8]

**Comment by mpowell14** [comment]
Either a good or a bad Lancelot is randomly selected. No one (besides Lancelot) knows which one (good or bad) is in the game. Merlin sees the Lancelot as one of the bad guys, regardless of whether it is good or bad to start with. The bad guys see the Lancelot but also do not know which alignment it currently has. Lancelot sees nothing.

**Comment by DylanDmitri** [comment]
oof
